# Generated by Django 5.0.6 on 2024-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intensity', models.CharField(max_length=20)),
                ('Likelihood', models.CharField(max_length=50)),
                ('Relevance', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=20)),
                ('Topics', models.CharField(max_length=10)),
                ('Region', models.CharField(max_length=5)),
                ('City', models.CharField(max_length=10)),
            ],
        ),
    ]
