# Generated by Django 5.0.6 on 2024-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalView', models.CharField(max_length=200)),
                ('revinew', models.IntegerField()),
                ('goThrow', models.CharField(max_length=100)),
            ],
        ),
    ]
