# Generated by Django 5.0.6 on 2024-05-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_rename_gothrow_dashboarddata_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dashboardData',
        ),
    ]
